import Head from "next/head";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Testimonials from "@/components/Testimonials";
import Contact from "@/components/Contact";
import Gallery from "@/components/Gallery";
import Places from "@/components/Places";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex flex-col grow">
        <Hero />
        <Places />
        <Gallery />
        <Testimonials />
        <Contact />
        {/* <p> Pricing </p>
        <p> Places </p> */}
      </main>
    </>
  );
}
